[package]
name = "game-theory-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tictactoe"
path = "src/tictactoe.rs"

[dependencies]
hashbrown = { version = "0.14.5", features = ["rayon"] }
rayon = "1.10.0"
