[package]
name = "game-theory-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tictactoe"
path = "src/tictactoe.rs"

[dependencies]
clap = "4.5.20"
hashbrown = "0.15.1"
rayon = "1.10.0"
rust_poker = "0.1.14"
